[functions]
  external_node_modules = ["express","@qwik-city-plan","@qwik-client-manifest","@qwik-city-not-found-paths","@qwik-city-static-paths","@qwik-city-sw-register"]
  node_bundler = "esbuild"
  directory = "src/functions"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/express/:splat"