[functions]
  external_node_modules = ["express","@qwik-city-plan"]
  node_bundler = "esbuild"
  directory = "src/functions"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/express/:splat"